[general]
import = [
    "~/themes/alacritty/ember.toml"
]

[terminal]
shell = "herdr"

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Mono" }

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
