[general]
import = [
    "~/themes/alacritty/ember.toml"
] 

[font]
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Mono" }


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
