[".gitignore"]
win = "~/.gitignore"

[Zellij]
win = "~/AppData/Roaming/Zellij"

[alacritty]
win = "~/AppData/Roaming/alacritty"

[herdr]
win = "~/AppData/Roaming/herdr"

[gitconfig-win]
win = "~/.gitconfig"

[mise]
win = "~/.config/mise"

[nvim]
win = "~/AppData/Local/nvim"
