[".gitignore"]
win = "~/.gitignore"

[Zellij]
win = "~/AppData/Roaming/Zellij"

[alacritty]
win = "~/AppData/Roaming/alacritty"

["config.toml"]
win = "config.toml"

[gitconfig-win]
win = "~/.gitconfig"

[mise]
win = "~/.config/mise"

[nvim]
win = "~/AppData/Local/nvim"
