[tools]
node = "24"
"github:anomalyco/opencode" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:eslint_d" = "latest"
"npm:hunkdiff" = "latest"
watchexec = "latest"
copilot = "latest"

[task_config]
includes = [
    "~/.dot/mise/tasks",
    ".config/mise/tasks",
    "tasks.toml",
    "mise.toml",
    "config.toml"
]

[tasks.clip]
description = "Copy output of a command to clipboard"
usage = '''arg "<command>" help="The command to run and copy its output"'''
run = "mise x node@24 -- npx clipboardy ${usage_command}"
run_windows = "clip < %usage_command%"
